### ISSUE TITLE
imutils.resize(image, width=400, height = 400) fails

### ISSUE THREAD

**Issue by WolfgangFahl** [rjgoodloe/ESE205-CVChess#5]
```
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "./OOPGUI.py", line 86, in <lambda>
    initBoardButton = tk.Button(self, text = "Done",font = MED_FONT, command = lambda : [controller.show_frame(SetBoardPage), controller.game.analyzeBoard()])
  File "/home/wf/source/python/ESE205-CVChess/Game.py", line 44, in analyzeBoard
    self.board = boardRec.initialize_Board()
  File "/home/wf/source/python/ESE205-CVChess/board_Recognition.py", line 34, in initialize_Board
    adaptiveThresh,img = self.clean_Image(image)
  File "/home/wf/source/python/ESE205-CVChess/board_Recognition.py", line 61, in clean_Image
    img = imutils.resize(image, width=400, height = 400)
  File "/usr/local/lib/python3.7/dist-packages/imutils/convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'tuple' object has no attribute 'shape'
```

**Comment by WolfgangFahl** [comment]
call of opencv() read returns two arguments
